[settings]
quiet = true

[tools]
poetry = "2.2"
python = "3.13"

[env]
_.python.venv = ".venv"

[tasks.dependencies]
alias = "deps"
description = "Install dependencies"
run = '''
#!/usr/bin/env bash

echo "===> Generating lock..."
poetry lock

echo "===> Installing dependencies..."
poetry install
'''

[tasks.format-check]
description = "Check code formatting (for workflow)"
run = '''
#!/usr/bin/env bash

echo "===> Checking formatting checkers for source..."
poetry run black --check {{config_root}}/src
poetry run isort --check {{config_root}}/src

echo "===> Checking formatting checkers for tests..."
poetry run black --check {{config_root}}/test
poetry run isort --check {{config_root}}/test
'''

[tasks.type-check]
alias = "type"
description = "Run type checker"
run = '''
#!/usr/bin/env bash

echo "===> Running type checker for source..."
poetry run pyright {{config_root}}/src

echo "===> Running type checker for tests..."
poetry run pyright {{config_root}}/test
'''

[tasks.lint]
description = "Run linter"
run = '''
#!/usr/bin/env bash

echo "===> Running linter for source..."
poetry run pylint {{config_root}}/src

echo "===> Running linter for tests..."
poetry run pylint {{config_root}}/test
'''

[tasks.check]
description = "Run type checker and linter"
run = '''
#!/usr/bin/env bash

mise run type-check
mise run lint
'''

[tasks.format]
alias = "fmt"
description = "Format code"
run = '''
#!/usr/bin/env bash

echo "===> Checking formatters for source..."
poetry run black {{config_root}}/src
poetry run isort {{config_root}}/src

echo "===> Checking formatters for tests..."
poetry run black {{config_root}}/test
poetry run isort {{config_root}}/test
'''

[tasks.test]
description = "Run tests"
run = '''
#!/usr/bin/env bash

echo "===> Running tests..."
poetry run pytest {{config_root}}/test
'''

[tasks.test-verbose]
alias = "testv"
description = "Run tests with verbose output"
run = '''
#!/usr/bin/env bash

echo "===> Running tests..."
poetry run pytest -vv {{config_root}}/test
'''

[tasks.fct]
description = "Format, check and test"
run = '''
#!/usr/bin/env bash

mise run format
mise run check
mise run test
'''
